spring.application.name=demoVero
spring.datasource.url =jdbc:postgresql://localhost:5432/base
spring.datasource.username=veronica
spring.datasource.password=1234
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
